events {}

http {
    include /etc/nginx/mime.types;

    # 1. БЛОК ДЛЯ ФРОНТЕНДА
    server {
        listen 80;
        server_name tpunion.students.nomorepartiessite.ru;

        root /usr/share/nginx/html;
        index index.html;

        location / {
            try_files $uri $uri/ /index.html;
        }

        location /content/ {
            proxy_pass http://backend:3000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }

    # 2. БЛОК ДЛЯ БЭКЕНДА (API)
    server {
        listen 80;
        server_name api.tpunion.students.nomorepartiessite.ru;

        # Перенаправляем абсолютно все запросы с этого домена на контейнер бэкенда
        location / {
            proxy_pass http://backend:3000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
}
